module.exports = [{
    "title": "Explore the City Center Just a Short Walk from this Idylic Villa",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Bend",
    "state": "Pennsylvania",
    "country": "United States",
    "cost": "$96.87",
    "capacity": 16,
    "bedrooms": 2,
    "beds": 4,
    "baths": 1,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Chic Loft",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Elliston",
    "state": "Hawaii",
    "country": "United States",
    "cost": "$178.47",
    "capacity": 7,
    "bedrooms": 1,
    "beds": 9,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Chic Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Room",
    "city": "Chloride",
    "state": "Kansas",
    "country": "United States",
    "cost": "$234.60",
    "capacity": 2,
    "bedrooms": 1,
    "beds": 7,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at this Idylic Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Corinne",
    "state": "Palau",
    "country": "United States",
    "cost": "$41.26",
    "capacity": 8,
    "bedrooms": 1,
    "beds": 14,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Posh Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Apartment",
    "city": "Marbury",
    "state": "Idaho",
    "country": "United States",
    "cost": "$208.03",
    "capacity": 2,
    "bedrooms": 7,
    "beds": 11,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Idylic Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Lemoyne",
    "state": "Ohio",
    "country": "United States",
    "cost": "$83.91",
    "capacity": 18,
    "bedrooms": 4,
    "beds": 8,
    "baths": 4,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Chic Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Airship",
    "city": "Websterville",
    "state": "Texas",
    "country": "United States",
    "cost": "$100.49",
    "capacity": 11,
    "bedrooms": 8,
    "beds": 3,
    "baths": "4.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Elegant Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Villa",
    "city": "National",
    "state": "Georgia",
    "country": "United States",
    "cost": "$153.20",
    "capacity": 20,
    "bedrooms": 5,
    "beds": 12,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Chic Bungalo",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Sussex",
    "state": "California",
    "country": "United States",
    "cost": "$192.92",
    "capacity": 18,
    "bedrooms": 3,
    "beds": 6,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Quiet Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Bungalo",
    "city": "Chical",
    "state": "North Carolina",
    "country": "United States",
    "cost": "$13.55",
    "capacity": 12,
    "bedrooms": 4,
    "beds": 12,
    "baths": "4.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at a Contemporary Villa",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Kieler",
    "state": "Arkansas",
    "country": "United States",
    "cost": "$92.20",
    "capacity": 5,
    "bedrooms": 2,
    "beds": 13,
    "baths": "4.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Picturesque Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Apartment",
    "city": "Shaft",
    "state": "Kentucky",
    "country": "United States",
    "cost": "$81.92",
    "capacity": 12,
    "bedrooms": 3,
    "beds": 5,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Posh Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Airship",
    "city": "Dexter",
    "state": "Missouri",
    "country": "United States",
    "cost": "$127.07",
    "capacity": 6,
    "bedrooms": 4,
    "beds": 1,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Chic Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Loft",
    "city": "Ypsilanti",
    "state": "Rhode Island",
    "country": "United States",
    "cost": "$123.67",
    "capacity": 5,
    "bedrooms": 7,
    "beds": 9,
    "baths": 4,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Modern Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Ellerslie",
    "state": "Virgin Islands",
    "country": "United States",
    "cost": "$55.20",
    "capacity": 4,
    "bedrooms": 5,
    "beds": 9,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Contemporary Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Otranto",
    "state": "North Dakota",
    "country": "United States",
    "cost": "$87.61",
    "capacity": 18,
    "bedrooms": 7,
    "beds": 2,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from this Idylic Penthouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Cresaptown",
    "state": "Massachusetts",
    "country": "United States",
    "cost": "$45.86",
    "capacity": 19,
    "bedrooms": 4,
    "beds": 3,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Contemporary Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Villa",
    "city": "Gwynn",
    "state": "Florida",
    "country": "United States",
    "cost": "$147.47",
    "capacity": 6,
    "bedrooms": 3,
    "beds": 11,
    "baths": 1,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at a Modern Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Loft",
    "city": "Dola",
    "state": "Utah",
    "country": "United States",
    "cost": "$69.29",
    "capacity": 14,
    "bedrooms": 6,
    "beds": 1,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from this Picturesque Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Loft",
    "city": "Osage",
    "state": "Virginia",
    "country": "United States",
    "cost": "$113.21",
    "capacity": 5,
    "bedrooms": 2,
    "beds": 2,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Elegant Loft",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Villa",
    "city": "Caroline",
    "state": "New Hampshire",
    "country": "United States",
    "cost": "$108.80",
    "capacity": 2,
    "bedrooms": 8,
    "beds": 11,
    "baths": "4.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Picturesque Villa",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Room",
    "city": "Springdale",
    "state": "New Jersey",
    "country": "United States",
    "cost": "$81.48",
    "capacity": 20,
    "bedrooms": 6,
    "beds": 7,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Chic Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Outlook",
    "state": "Wyoming",
    "country": "United States",
    "cost": "$191.92",
    "capacity": 12,
    "bedrooms": 5,
    "beds": 12,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Elegant Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Penthouse",
    "city": "Riverton",
    "state": "Oregon",
    "country": "United States",
    "cost": "$139.42",
    "capacity": 12,
    "bedrooms": 8,
    "beds": 10,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Quiet Apartment",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Makena",
    "state": "Illinois",
    "country": "United States",
    "cost": "$110.39",
    "capacity": 8,
    "bedrooms": 3,
    "beds": 5,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Quiet Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Airship",
    "city": "Richford",
    "state": "Nevada",
    "country": "United States",
    "cost": "$213.19",
    "capacity": 12,
    "bedrooms": 7,
    "beds": 5,
    "baths": "4.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Modern Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Townhouse",
    "city": "Libertytown",
    "state": "Washington",
    "country": "United States",
    "cost": "$81.97",
    "capacity": 16,
    "bedrooms": 5,
    "beds": 12,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Quiet Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Emison",
    "state": "West Virginia",
    "country": "United States",
    "cost": "$242.76",
    "capacity": 14,
    "bedrooms": 7,
    "beds": 7,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Chic Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Airship",
    "city": "Coloma",
    "state": "Colorado",
    "country": "United States",
    "cost": "$182.68",
    "capacity": 11,
    "bedrooms": 1,
    "beds": 1,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at a Modern Penthouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Wadsworth",
    "state": "Arizona",
    "country": "United States",
    "cost": "$97.98",
    "capacity": 4,
    "bedrooms": 8,
    "beds": 4,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at a Contemporary Loft",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Loft",
    "city": "Vaughn",
    "state": "Indiana",
    "country": "United States",
    "cost": "$248.60",
    "capacity": 11,
    "bedrooms": 6,
    "beds": 1,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at a Contemporary Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Loft",
    "city": "Clarksburg",
    "state": "Montana",
    "country": "United States",
    "cost": "$146.01",
    "capacity": 10,
    "bedrooms": 8,
    "beds": 9,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Quiet Bungalo",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Loft",
    "city": "Castleton",
    "state": "Iowa",
    "country": "United States",
    "cost": "$211.60",
    "capacity": 18,
    "bedrooms": 8,
    "beds": 4,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at a Chic Airship",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Williams",
    "state": "Nebraska",
    "country": "United States",
    "cost": "$20.85",
    "capacity": 9,
    "bedrooms": 3,
    "beds": 13,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Picturesque Bungalo",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Townhouse",
    "city": "Thornport",
    "state": "Connecticut",
    "country": "United States",
    "cost": "$12.84",
    "capacity": 15,
    "bedrooms": 2,
    "beds": 12,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Posh Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Drytown",
    "state": "Alabama",
    "country": "United States",
    "cost": "$102.46",
    "capacity": 5,
    "bedrooms": 6,
    "beds": 1,
    "baths": 4,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Modern Penthouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Belva",
    "state": "Maryland",
    "country": "United States",
    "cost": "$42.57",
    "capacity": 12,
    "bedrooms": 2,
    "beds": 15,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Idylic Penthouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Penthouse",
    "city": "Denio",
    "state": "Vermont",
    "country": "United States",
    "cost": "$57.40",
    "capacity": 11,
    "bedrooms": 6,
    "beds": 3,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Contemporary Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Room",
    "city": "Berlin",
    "state": "American Samoa",
    "country": "United States",
    "cost": "$133.14",
    "capacity": 3,
    "bedrooms": 4,
    "beds": 2,
    "baths": 4,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Picturesque Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Penthouse",
    "city": "Jackpot",
    "state": "Marshall Islands",
    "country": "United States",
    "cost": "$63.95",
    "capacity": 20,
    "bedrooms": 7,
    "beds": 15,
    "baths": "4.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Chic Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Airship",
    "city": "Bison",
    "state": "Oklahoma",
    "country": "United States",
    "cost": "$236.38",
    "capacity": 10,
    "bedrooms": 7,
    "beds": 13,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Modern Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Villa",
    "city": "Wacissa",
    "state": "Louisiana",
    "country": "United States",
    "cost": "$249.75",
    "capacity": 6,
    "bedrooms": 8,
    "beds": 9,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at a Modern Airship",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Airship",
    "city": "Blanford",
    "state": "Wisconsin",
    "country": "United States",
    "cost": "$240.55",
    "capacity": 5,
    "bedrooms": 1,
    "beds": 10,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Quiet Airship",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Airship",
    "city": "Babb",
    "state": "South Dakota",
    "country": "United States",
    "cost": "$230.78",
    "capacity": 8,
    "bedrooms": 5,
    "beds": 2,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at a Chic Villa",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Bungalo",
    "city": "Saddlebrooke",
    "state": "Michigan",
    "country": "United States",
    "cost": "$86.88",
    "capacity": 2,
    "bedrooms": 1,
    "beds": 4,
    "baths": 4,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from this Elegant Loft",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Apartment",
    "city": "Ronco",
    "state": "New Mexico",
    "country": "United States",
    "cost": "$121.96",
    "capacity": 9,
    "bedrooms": 3,
    "beds": 15,
    "baths": 1,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Picturesque Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Loft",
    "city": "Cutter",
    "state": "Delaware",
    "country": "United States",
    "cost": "$56.75",
    "capacity": 11,
    "bedrooms": 5,
    "beds": 8,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Picturesque Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Dundee",
    "state": "New York",
    "country": "United States",
    "cost": "$97.00",
    "capacity": 17,
    "bedrooms": 6,
    "beds": 15,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at a Modern Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Villa",
    "city": "Rivereno",
    "state": "Puerto Rico",
    "country": "United States",
    "cost": "$249.16",
    "capacity": 3,
    "bedrooms": 4,
    "beds": 2,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Contemporary Bungalo",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Airship",
    "city": "Bergoo",
    "state": "Tennessee",
    "country": "United States",
    "cost": "$208.18",
    "capacity": 9,
    "bedrooms": 6,
    "beds": 12,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Idylic Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Barstow",
    "state": "South Carolina",
    "country": "United States",
    "cost": "$69.79",
    "capacity": 16,
    "bedrooms": 1,
    "beds": 15,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Modern Loft",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Loft",
    "city": "Bangor",
    "state": "Federated States Of Micronesia",
    "country": "United States",
    "cost": "$239.89",
    "capacity": 7,
    "bedrooms": 3,
    "beds": 5,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Modern Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Emerald",
    "state": "Maine",
    "country": "United States",
    "cost": "$112.89",
    "capacity": 20,
    "bedrooms": 7,
    "beds": 12,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Idylic Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Airship",
    "city": "Moscow",
    "state": "Northern Mariana Islands",
    "country": "United States",
    "cost": "$28.97",
    "capacity": 3,
    "bedrooms": 7,
    "beds": 3,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Quiet Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Villa",
    "city": "Bennett",
    "state": "Alaska",
    "country": "United States",
    "cost": "$189.76",
    "capacity": 4,
    "bedrooms": 8,
    "beds": 14,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Modern Airship",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Benson",
    "state": "Minnesota",
    "country": "United States",
    "cost": "$180.43",
    "capacity": 13,
    "bedrooms": 7,
    "beds": 14,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Quiet Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Villa",
    "city": "Lorraine",
    "state": "Mississippi",
    "country": "United States",
    "cost": "$177.80",
    "capacity": 7,
    "bedrooms": 2,
    "beds": 11,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from this Quiet Loft",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Townhouse",
    "city": "Darbydale",
    "state": "Guam",
    "country": "United States",
    "cost": "$226.43",
    "capacity": 10,
    "bedrooms": 5,
    "beds": 1,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Quiet Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Brooktrails",
    "state": "Pennsylvania",
    "country": "United States",
    "cost": "$149.60",
    "capacity": 8,
    "bedrooms": 6,
    "beds": 2,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Modern Apartment",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Room",
    "city": "Blackgum",
    "state": "Hawaii",
    "country": "United States",
    "cost": "$216.83",
    "capacity": 20,
    "bedrooms": 6,
    "beds": 13,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Contemporary Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Townhouse",
    "city": "Canterwood",
    "state": "Kansas",
    "country": "United States",
    "cost": "$181.24",
    "capacity": 4,
    "bedrooms": 3,
    "beds": 11,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Elegant Bungalo",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Villa",
    "city": "Rockingham",
    "state": "Palau",
    "country": "United States",
    "cost": "$176.85",
    "capacity": 13,
    "bedrooms": 3,
    "beds": 15,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at this Idylic Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Room",
    "city": "Alafaya",
    "state": "Idaho",
    "country": "United States",
    "cost": "$188.62",
    "capacity": 8,
    "bedrooms": 5,
    "beds": 4,
    "baths": 4,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Chic Apartment",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Penthouse",
    "city": "Catherine",
    "state": "Ohio",
    "country": "United States",
    "cost": "$19.19",
    "capacity": 2,
    "bedrooms": 3,
    "beds": 7,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Posh Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Townhouse",
    "city": "Chase",
    "state": "Texas",
    "country": "United States",
    "cost": "$93.75",
    "capacity": 6,
    "bedrooms": 3,
    "beds": 6,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at this Idylic Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Apartment",
    "city": "Tyhee",
    "state": "Georgia",
    "country": "United States",
    "cost": "$117.57",
    "capacity": 15,
    "bedrooms": 8,
    "beds": 15,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Contemporary Apartment",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Kenmar",
    "state": "California",
    "country": "United States",
    "cost": "$73.65",
    "capacity": 15,
    "bedrooms": 6,
    "beds": 4,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Elegant Villa",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Loft",
    "city": "Conestoga",
    "state": "North Carolina",
    "country": "United States",
    "cost": "$78.57",
    "capacity": 9,
    "bedrooms": 6,
    "beds": 10,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at a Posh Bungalo",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Dellview",
    "state": "Arkansas",
    "country": "United States",
    "cost": "$153.30",
    "capacity": 4,
    "bedrooms": 5,
    "beds": 10,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Posh Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Downsville",
    "state": "Kentucky",
    "country": "United States",
    "cost": "$183.45",
    "capacity": 9,
    "bedrooms": 8,
    "beds": 8,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Chic Penthouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Lowell",
    "state": "Missouri",
    "country": "United States",
    "cost": "$80.35",
    "capacity": 16,
    "bedrooms": 4,
    "beds": 9,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Quiet Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Villa",
    "city": "Ilchester",
    "state": "Rhode Island",
    "country": "United States",
    "cost": "$146.41",
    "capacity": 16,
    "bedrooms": 4,
    "beds": 1,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Modern Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Airship",
    "city": "Coral",
    "state": "Virgin Islands",
    "country": "United States",
    "cost": "$18.10",
    "capacity": 4,
    "bedrooms": 8,
    "beds": 7,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Quiet Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Airship",
    "city": "Smeltertown",
    "state": "North Dakota",
    "country": "United States",
    "cost": "$48.04",
    "capacity": 8,
    "bedrooms": 1,
    "beds": 8,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Posh Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Room",
    "city": "Joppa",
    "state": "Massachusetts",
    "country": "United States",
    "cost": "$201.92",
    "capacity": 19,
    "bedrooms": 8,
    "beds": 3,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Quiet Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Garfield",
    "state": "Florida",
    "country": "United States",
    "cost": "$219.79",
    "capacity": 12,
    "bedrooms": 8,
    "beds": 9,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Posh Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Bonanza",
    "state": "Utah",
    "country": "United States",
    "cost": "$60.39",
    "capacity": 17,
    "bedrooms": 6,
    "beds": 7,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Contemporary Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Airship",
    "city": "Dowling",
    "state": "Virginia",
    "country": "United States",
    "cost": "$122.10",
    "capacity": 20,
    "bedrooms": 1,
    "beds": 6,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Picturesque Apartment",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Penthouse",
    "city": "Grayhawk",
    "state": "New Hampshire",
    "country": "United States",
    "cost": "$75.71",
    "capacity": 3,
    "bedrooms": 2,
    "beds": 3,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from this Picturesque Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Warren",
    "state": "New Jersey",
    "country": "United States",
    "cost": "$169.42",
    "capacity": 5,
    "bedrooms": 4,
    "beds": 13,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from this Picturesque Apartment",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Villa",
    "city": "Cleary",
    "state": "Wyoming",
    "country": "United States",
    "cost": "$182.18",
    "capacity": 16,
    "bedrooms": 5,
    "beds": 13,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at a Chic Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Airship",
    "city": "Coaldale",
    "state": "Oregon",
    "country": "United States",
    "cost": "$137.42",
    "capacity": 20,
    "bedrooms": 5,
    "beds": 1,
    "baths": 1,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Modern Bungalo",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Bungalo",
    "city": "Fannett",
    "state": "Illinois",
    "country": "United States",
    "cost": "$225.07",
    "capacity": 9,
    "bedrooms": 8,
    "beds": 11,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at this Idylic Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Cetronia",
    "state": "Nevada",
    "country": "United States",
    "cost": "$17.25",
    "capacity": 9,
    "bedrooms": 5,
    "beds": 10,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Idylic Bungalo",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Apartment",
    "city": "Grapeview",
    "state": "Washington",
    "country": "United States",
    "cost": "$99.33",
    "capacity": 12,
    "bedrooms": 2,
    "beds": 15,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at a Modern Bungalo",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Loft",
    "city": "Sehili",
    "state": "West Virginia",
    "country": "United States",
    "cost": "$215.08",
    "capacity": 18,
    "bedrooms": 6,
    "beds": 10,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Modern Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Penthouse",
    "city": "Sheatown",
    "state": "Colorado",
    "country": "United States",
    "cost": "$138.52",
    "capacity": 10,
    "bedrooms": 4,
    "beds": 11,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Idylic Airship",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Greenbackville",
    "state": "Arizona",
    "country": "United States",
    "cost": "$76.35",
    "capacity": 20,
    "bedrooms": 3,
    "beds": 8,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Unwind at this Quiet Loft",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Townhouse",
    "city": "Catharine",
    "state": "Indiana",
    "country": "United States",
    "cost": "$165.92",
    "capacity": 10,
    "bedrooms": 6,
    "beds": 1,
    "baths": "2.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Chic Apartment",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Apartment",
    "city": "Nanafalia",
    "state": "Montana",
    "country": "United States",
    "cost": "$122.21",
    "capacity": 6,
    "bedrooms": 8,
    "beds": 12,
    "baths": "3.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Kick Back and Relax at this Idylic Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Airship",
    "city": "Fillmore",
    "state": "Iowa",
    "country": "United States",
    "cost": "$240.43",
    "capacity": 5,
    "bedrooms": 5,
    "beds": 10,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Shops from a Modern Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Villa",
    "city": "Muse",
    "state": "Nebraska",
    "country": "United States",
    "cost": "$212.25",
    "capacity": 19,
    "bedrooms": 5,
    "beds": 5,
    "baths": 4,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Chic Villa",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Loft",
    "city": "Leroy",
    "state": "Connecticut",
    "country": "United States",
    "cost": "$56.00",
    "capacity": 13,
    "bedrooms": 7,
    "beds": 12,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Quiet Airship",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Delwood",
    "state": "Alabama",
    "country": "United States",
    "cost": "$193.92",
    "capacity": 5,
    "bedrooms": 6,
    "beds": 8,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Walk to the Beach from a Chic Penthouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Apartment",
    "city": "Robbins",
    "state": "Maryland",
    "country": "United States",
    "cost": "$136.43",
    "capacity": 16,
    "bedrooms": 2,
    "beds": 12,
    "baths": 3,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Modern Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Townhouse",
    "city": "Harrison",
    "state": "Vermont",
    "country": "United States",
    "cost": "$48.79",
    "capacity": 6,
    "bedrooms": 1,
    "beds": 12,
    "baths": "4.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in this Quiet Airship",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Room",
    "city": "Coinjock",
    "state": "American Samoa",
    "country": "United States",
    "cost": "$180.85",
    "capacity": 8,
    "bedrooms": 6,
    "beds": 1,
    "baths": "0.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from a Contemporary Townhouse",
    "description": "Relaxing refuge set on a lush hillside in the quiet seaside town of Stinson Beach. Feel transported by the authentic Japanese design aesthetic of handmade shoji screens and the tranquilizing outdoor shower and soaking tub. Forest Bath in the Bay Laurels that surround you. Indulge in treetop ocean views from the comfort of a queen bed, and watch the sun set from the privacy of a wooden deck. When it’s time to hit the beach, it’s only a minutes’ walk away from the bottom of the stairs.",
    "type": "Bungalo",
    "city": "Gerber",
    "state": "Marshall Islands",
    "country": "United States",
    "cost": "$129.58",
    "capacity": 13,
    "bedrooms": 4,
    "beds": 13,
    "baths": "1.5",
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Relax in Luxury in a Modern Penthouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Rew",
    "state": "Oklahoma",
    "country": "United States",
    "cost": "$122.86",
    "capacity": 5,
    "bedrooms": 7,
    "beds": 8,
    "baths": 2,
    "photoUrl": "http://placeholder.com"
  },
  {
    "title": "Explore the City Center Just a Short Walk from this Quiet Townhouse",
    "description": "Retreat to the deck of this sustainable getaway and gaze at the twinkling constellations under a cosy tartan blanket. AirShip 2 is an iconic, insulated aluminium pod designed by Roderick James with views of the Sound of Mull from dragonfly windows.",
    "type": "Apartment",
    "city": "Jenkinsville",
    "state": "Louisiana",
    "country": "United States",
    "cost": "$234.95",
    "capacity": 16,
    "bedrooms": 5,
    "beds": 15,
    "baths": 5,
    "photoUrl": "http://placeholder.com"
  }
];